name: "Tokenized Commit"
description: "Commits a single file change"
inputs:
  file-path:
    description: "The path of the file to include"
    required: true
  file-content:
    description: "The base64 encoded file content"
    required: true
  branch:
    description: "The branch to commit to"
    required: true
  message:
    description: "The commit message"
    required: true
  appId:
    description: "The github app id"
    required: true
  appKey:
    description: "The github app private key"
    required: true


runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Generate a token
      id: generate-token
      uses: tibdex/github-app-token@32691ba7c9e7063bd457bd8f2a5703138591fa58 # v1.9.0
      with:
        app_id: ${{ inputs.appId }}
        private_key: ${{ inputs.appKey }}

    - name: Commit changes (SIGNED)
      shell: bash
      env:
        GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        FILE_TO_COMMIT: ${{ inputs.file-path }}
        DESTINATION_BRANCH: ${{ inputs.branch }}
        MESSAGE: ${{ inputs.message }}
        CONTENT: ${{ inputs.file-content }}
      run: |
        export SHA=$( git rev-parse $DESTINATION_BRANCH:$FILE_TO_COMMIT )
        gh api --method PUT /repos/ThembaniFubesi/actions_test/contents/$FILE_TO_COMMIT \
          --field message="$MESSAGE" \
          --field content="$CONTENT" \
          --field encoding="base64" \
          --field branch="$DESTINATION_BRANCH" \
          --field sha="$SHA"
