# This Pipeline delivers APK and signed IPA builds to the manual qa team for
# the Mecca Bingo Application.
# It runs when a PR is merged into one of the specified branches and has the label 'Mecca'

name: mb-qa-distribution-pipeline

env:
  ACTIONS_RUNNER_DEBUG: true

on:
  push:
    branches: ["main"]

jobs:
  build-apps:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      #################################
      # Get App Version from pubspec.yaml
      #################################
      - uses: actions/checkout@v4
      - name: Get App Version from pubspec.yaml
        shell: bash
        run: |
          echo "APP_VERSION=$(cat pubspec.yaml | grep -m 1 -o 'version:[^:]*' | cut -f2 -d":" | xargs)" >> $GITHUB_ENV

      
      

      #################################
      # Get Latest Release Version
      #################################
      - name: Get Latest Release Version
        shell: bash
        env:
          ACTIONS_STEP_DEBUG: true
        run: |
          build_name=$(echo "$APP_VERSION" | sed 's/+.*//')
          echo "BUILD_NAME=$build_name" >> $GITHUB_ENV
          build_number=$(echo "$APP_VERSION" | sed 's/.*+//')

          ((build_number++))

          echo "BUILD_NUMBER=$build_number" >> $GITHUB_ENV
          echo $build_number
      
      - uses: actions/checkout@v4
      - name: Increment Version
        shell: bash
        run: |
          new_version="${{env.BUILD_NAME}}+${{env.BUILD_NUMBER}}" 
          sed -i '' -E "s/version: ([0-9]+\.[0-9]+\.[0-9]+\+[0-9]+)/version: 20/" ./pubspec.yaml

      - name: Display
        shell: bash
        run: |
          echo v.${{env.BUILD_NAME}}
          echo v.${{env.BUILD_NUMBER}}
