# This Pipeline delivers APK and signed IPA builds to the manual qa team for
# the Mecca Bingo Application.
# It runs when a PR is merged into one of the specified branches and has the label 'Mecca'

name: test-pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-apps:
    runs-on: macos-14
    timeout-minutes: 60
    steps:
      #################################
      # Get App Version from pubspec.yaml
      #################################
      - uses: actions/checkout@v4
      - name: Get App Version from pubspec.yaml
        shell: bash
        run: |
          echo "APP_VERSION=$(cat pubspec.yaml | grep -m 1 -o 'version:[^:]*' | cut -f2 -d":" | xargs)" >> $GITHUB_ENV
      #################################
      # Get Latest Release Version
      #################################
      - name: Get Latest Release Version
        shell: bash
        env:
          ACTIONS_STEP_DEBUG: true
        run: |
          build_name=$(echo "$APP_VERSION" | sed 's/+.*//')
          echo "BUILD_NAME=$build_name" >> $GITHUB_ENV
          build_number=$(echo "$APP_VERSION" | sed 's/.*+//')

          ((build_number++))

          echo "BUILD_NUMBER=$build_number" >> $GITHUB_ENV
          echo $build_number
      
      - name: Increment Version
        uses: ./.github/actions/increment-release
        with:
          project-path: 'sd'
          build_name: ${{env.BUILD_NAME}}
          build_number: ${{env.BUILD_NUMBER}}

      - name: Set and encode file content variable
        shell: bash
        run: |
          echo "FILE_CONTENT=$(base64 -i pubspec.yaml)" >> $GITHUB_ENV
      - name: Tokenized Commit
        uses: ./.github/actions/tokenized-commit
        with:
          file-path: pubspec.yaml
          file-content: ${{ env.FILE_CONTENT }}
          branch: ${{ github.ref_name }}
          message: "chore: bump version [skip ci]"
          appId: ${{ secrets.BRANCH_COMMIT_APP_ID }}
          appKey: ${{ secrets.BRANCH_COMMIT_APP_KEY }}
